name: Docker

on:
  push:
    # Pushing to `main` branch builds image with `:latest` tag.
    branches:
      - main

    # Pushing `v1.2.3` tags builds accordingly tagged images
    tags:
      - v*

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prepare
        run: |
          FULL_IMAGE_NAME=ghcr.io/${{ github.repository }}

          ## Change all uppercase to lowercase
          FULL_IMAGE_NAME=$(echo $FULL_IMAGE_NAME | tr '[A-Z]' '[a-z]')

          ## Strip git ref prefix from tag
          TAG=$(echo "${{ github.event.ref }}" | sed -e 's,.*/\(.*\),\1,')

          ## Strip "v" prefix from tag name
          [[ "${{ github.event.ref }}" == "refs/tags/"* ]] && TAG=$(echo $TAG | sed -e 's/^v//')

          ## Use Docker `latest` tag convention
          [ "$TAG" == "main" ] && TAG=latest

          echo "::set-output name=img::${FULL_IMAGE_NAME}"
          echo "::set-output name=tag::${TAG}"

      - name: Build & push image
        run: |
          BUILDER_VERSION=${{ steps.prepare.outputs.tag }}-builder

          [[ "$BUILDER_VERSION" == "latest-builder" ]] && BUILDER_VERSION=builder-latest
          [[ "$BUILDER_VERSION" == *"-alpine-builder"* ]] && BUILDER_VERSION=$(echo $BUILDER_VERSION | sed -r 's!^(.+)(-alpine)(-builder)!\1\3\2!g')

          docker build \
            --file Dockerfile \
            --tag ${{ steps.prepare.outputs.img }}:${{ steps.prepare.outputs.tag }} \
            --build-arg CADDY_VERSION=${{ steps.prepare.outputs.tag }} \
            --build-arg BUILDER_VERSION=${BUILDER_VERSION} \
            .

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          docker push ${{ steps.prepare.outputs.img }}:${{ steps.prepare.outputs.tag }}
